pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - author~=^dependabot\[bot\]$
      - "#check-failure=0"
      - "#check-pending=0"
    actions:
      merge:
        method: squash

  - name: Automatic merge for changeset release PRs
    conditions:
      - author=github-actions[bot]
      - head~=^changeset-release/
      - "#check-failure=0"
      - "#check-pending=0"
    actions:
      merge:
        method: squash
